name: LaTeX2WordPress Automation

on:
  push:
    branches:
      - main

env:
  USUARIO: ${{ secrets.USUARIO }}
  USUARIO_SERV: ${{ secrets.USUARIO_SERV }}
  CONTRASENIA_SERV: ${{ secrets.CONTRASENIA_SERV }}
  CONTRASENIA: ${{ secrets.CONTRASENIA }}
  CLOUDFLARE_ZONE_ALEPH: ${{ secrets.CLOUDFLARE_ZONE_ALEPH }}
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  CLOUDFLARE_CORREO: ${{ secrets.CLOUDFLARE_CORREO }}
  WP_URL: ${{ vars.WP_URL }}

jobs:
  run-latex2wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Verify Pandoc installation
      run: pandoc --version
      
    - name: Move files to home directory
      run: |
        cp LaTeX2WordPress.py $HOME/LaTeX2WordPress.py
        cp ./Cap14/Problema0959.tex $HOME/Problema0959.tex
        cp ./Portada.jpeg $HOME/Portada.jpeg
        cp ./aleph-comandos.sty $HOME/aleph-comandos.sty

    - name: Run LaTeX2WordPress script
      run: |
        echo "Running LaTeX2WordPress with user $USUARIO"
        python $HOME/LaTeX2WordPress.py $HOME/Problema0959.tex $HOME/Portada.jpeg
